src/Entity/AssetType.php
<?php

declare(strict_types=1);

namespace Groshy\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\CustomIdGenerator;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\Index;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping\Table;
use Gedmo\Mapping\Annotation as Gedmo;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Symfony\Component\Serializer\Annotation\Groups;
use Talav\Component\Resource\Model\ResourceInterface;
use Talav\Component\Resource\Model\ResourceTrait;

#[Entity]
#[Table(name: 'asset_type')]
#[Index(columns: ['is_asset'])]
#[Index(columns: ['position'])]
#[ApiResource(
    collectionOperations: [
        'get' => [
            'normalization_context' => [
                'groups' => ['assetType:collection:read'],
                'swagger_definition_name' => 'Collection Read',
            ],
        ],
    ],
    itemOperations: [
        'get' => [
            'normalization_context' => [
                'groups' => ['assetType:item:read'],
                'swagger_definition_name' => 'Item Read',
            ],
        ],
    ],
)]
class AssetType implements ResourceInterface
{
    use ResourceTrait;

    #[Id]
    #[Column(type: 'uuid', unique: true)]
    #[GeneratedValue(strategy: 'CUSTOM')]
    #[CustomIdGenerator(class: UuidGenerator::class)]
    #[Groups(['assetType:item:read', 'assetType:collection:read'])]
    protected mixed $id;

    #[Column(type: 'string', length: 250)]
    #[Groups(['assetType:item:read', 'assetType:collection:read'])]
    protected ?string $name;

    #[Column(type: 'integer')]
    protected int $position = 0;

    #[Column(name: 'is_asset', type: 'boolean')]
    protected bool $isAsset = true;

    #[Column(name:'is_active', type: 'boolean')]
    protected bool $isActive = true;

    #[Column(type: 'string', length: 250, unique: true)]
    #[Gedmo\Slug(fields: ['name'])]
    #[Groups(['assetType:item:read', 'assetType:collection:read'])]
    protected ?string $slug;

    #[OneToMany(mappedBy: 'parent', targetEntity: AssetType::class)]
    protected Collection $children;

    #[ManyToOne(targetEntity: AssetType::class, inversedBy: 'children')]
    #[Groups(['assetType:item:read', 'assetType:collection:read'])]
    protected ?AssetType $parent;

    public function __construct()
    {
        $this->children = new ArrayCollection();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function isAsset(): bool
    {
        return $this->isAsset;
    }

    public function setIsAsset(bool $isAsset): void
    {
        $this->isAsset = $isAsset;
    }

    public function isActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): void
    {
        $this->isActive = $isActive;
    }

    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChild(ArrayCollection|Collection $children): void
    {
        $this->children = $children;
    }

    public function getParent(): ?AssetType
    {
        return $this->parent;
    }

    public function setParent(?AssetType $parent): void
    {
        $this->parent = $parent;
    }

    public function getPosition(): int
    {
        return $this->position;
    }

    public function setPosition(int $position): void
    {
        $this->position = $position;
    }

    public function isTopLevel(): bool
    {
        return is_null($this->getParent());
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }
}

src/Controller/Frontend/DashboardController.php
<?php

namespace Groshy\Controller\Frontend;

use DateTime;
use Groshy\Provider\DashboardProvider;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Talav\Component\Resource\Repository\RepositoryInterface;

class DashboardController extends AbstractController
{
    public function __construct(
        private readonly DashboardProvider $provider,
        private readonly RepositoryInterface $positionRepository,
        private readonly RepositoryInterface $assetTypeRepository,
        private readonly RepositoryInterface $transactionRepository,
        private readonly RepositoryInterface $positionValueRepository,
    ) {
    }

    /**
     * @Route("/user/dashboard")
     */
    public function dashboardAction(Request $request): Response
    {
        $to = DateTime::createFromFormat('Y-m-d', $request->query->get('to'));
        $from = DateTime::createFromFormat('Y-m-d', $request->query->get('from'));
        $mainType = $this->assetTypeRepository->getDashboardType();

        return $this->render('dashboard/dashboard.html.twig', [
            'from' => $from,
            'to' => $to,
            'dash' => $this->provider->getDashboardData($from, $to, $this->getUser()),
            'maxDate' => $this->positionValueRepository->getFirstDate($this->getUser()),
            'positions' => $this->positionRepository->byType($mainType, $this->getUser()),
            'transactions' => $this->transactionRepository->byType($mainType, $this->getUser()),
            'sponsors' => $this->positionRepository->groupBySponsor($this->getUser()),
            'years' => $this->positionRepository->groupByYear($this->getUser()),
        ]);
    }
}

templates/dashboard/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    Breadcrumbs: {{ knp_menu_render('breadcrumbs_dashboard') }}
    <h1>Dashboard page</h1>
    {% if dash|length > 0 %}
    From: {{ from|date("m/d/Y") }}
    To: {{ to|date("m/d/Y") }}
    <div>
        {% if maxDate is not null %}
            Value for MAX data filter: {{ maxDate|date("m/d/Y")  }}
        {% else %}
            Do not show MAX date filter
        {% endif %}
    </div>
    <div>
        <h4>Top Graph data</h4>
        {% for date, value in dash.total.value.graph %}
            <li>{{ date }}: {{ value}}</li>
        {% endfor %}
    </div>
    <div>
        Net Worth: {{ dash.total.value.current }}
    </div>
    <div>
        Return: ${{ dash.total.value.change.amount }}, {{ dash.total.value.change.percent }}%
    </div>
    <div>
        Assets: ${{ dash.assets.value.current   }}
        Liabilities: ${{ dash.liabilities.value.current  }}
    </div>
    <div>
        Asset Allocation:
        {% for assetTypeTracker in dash.root_types %}
            <div>
                <div>
                    <a href="{{ path('groshy_frontend_assettype_assets', {'slug': assetTypeTracker.trackable.id })}}">{{ assetTypeTracker.trackable.name }}</a>
                </div>
                <div>{{ assetTypeTracker.value.current }}</div>
                <div>{{ assetTypeTracker.value.change.amount }}</div>
                <div>{{ assetTypeTracker.value.change.percent }}</div>
                <div>{{ assetTypeTracker.allocation.current }}</div>
                <div>{{ assetTypeTracker.allocation.change.percent }}</div>
                <div>
                    {% for date, value in assetTypeTracker.allocation.graph %}
                        <li>{{ date }}: {{ value}}</li>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    <div>
        Real Estate
    </div>
    <div>
        Last investments
        {% for position in positions %}
            <div>{{ position.asset.name }}</div>
            <div>{{ position.startDate|date("m/d/Y") }}</div>
            <div>{{ position.data.capitalCommitment }}</div>
        {% endfor %}
    </div>
    <div>
        Last transactions
        {% for transaction in transactions %}
            <div>{{ transaction.position.asset.name }}</div>
            <div>{{ transaction.valueDate|date("m/d/Y") }}</div>
            <div>{{ transaction.value }}</div>
        {% endfor %}
    </div>
    <div>
        Top Sponsors
        {% for sponsor in sponsors %}
            <div>{{ sponsor.name }}</div>
            <div>{{ sponsor.total }}</div>
        {% endfor %}
    </div>
    <div>
        Years
        {% for year in years %}
            <div>{{ year.year }}</div>
            <div>{{ year.total }}</div>
        {% endfor %}
    </div>
    {% else %}
        Empty Dashboard page
    {% endif %}

{% endblock %}